# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [6]:
A = np.arange(1, 16).reshape(3,5)

In [7]:

print(A.dtype)
print()

print(A.size)
print()

print(A.shape)
print()

print(A.ndim)
print()

int32

15

(3, 5)

2



### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [8]:
print(B - C)
print()

print(B * C)
print()

print(B @ C)
print()

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]



### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [9]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(np.exp(B))
print()

print(np.min(B))
print(np.min(B, axis = 0))
print(np.min(B, axis = 1))
print()

print(np.argmin(B))
print(np.argmin(B, axis = 0))
print()

print(np.sum(B))
print(np.mean(B, axis = 1))
print(np.median(B, axis = 1))


[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1
[1 2 3]
[1 4 7]

0
[0 0 0]

45
[2. 5. 8.]
[2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [12]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [13]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
# When we dealing with fewer indices than the number of axes, then the missing indices are treated as full slices. 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [14]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [16]:
for i in A.flatten():
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [17]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# There are two matrices and each one of them have 3 rows and suitable number of columns. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [18]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

print(m1.shape)
print(m2.shape)

[[2 3]
 [4 5]]
(2, 2)
(2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [19]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [24]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

print()
print(A+b)

[[1 2]
 [3 4]]
[2 2]

[[3 4]
 [5 6]]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [ ]:
# 10.1.1

In [ ]:
# a)
x = (4, 3)
# The vector dimension is 1 x 2. 

In [52]:
# b)
x = np.array([4, 3])
result = 5 * x
print(result)

[20 15]


In [42]:
# c)
x = np.array([4, 3])
result = 3 * x
print(result)

[12  9]


In [45]:
# d)
x = np.array([4, 3])
result = 5 * x - 3 * x
print(result)

[8 6]


In [44]:
# e)
x = np.array([4, 3])
result = 8 * x
print(result)

[32 24]


In [46]:
# f)
x = np.array([4, 3])
result = 4 * x - x
print(result)

[12  9]


In [47]:
# g)
x = np.array([4, 3])
print(x)
print(x.T)

[4 3]
[4 3]


In [61]:
# i)
x = np.array([4, 3])
np.linalg.norm(x)

5.0

In [ ]:
# 10.1.2

In [ ]:
# a)
v = is a 4-dimensional vector

In [53]:
# b)
v = np.array([3, 7, 0, 11])
s = 2

v*2

array([ 6, 14,  0, 22])

In [54]:
# c)
v = np.array([3, 7, 0, 11])
s = (5 + 2)
v*s

array([21, 49,  0, 77])

In [55]:
# d)
v = np.array([3, 7, 0, 11])
s = (4 - 2)
v*s

array([ 6, 14,  0, 22])

In [56]:
# e)
v = np.array([3, 7, 0, 11])
print(v)
print(v.T)

[ 3  7  0 11]
[ 3  7  0 11]


In [60]:
# f)
v = np.array([3, 7, 0, 11])
np.linalg.norm(v)


13.379088160259652

In [ ]:
# 10.1.3

In [71]:
v1 = np.array([4, 3, 1, 5])
v2 = np.array([12, 3, 1, 1])
# a)
np.linalg.norm(v1)

7.14142842854285

In [72]:
# b)
v1 = np.array([4, 3, 1, 5])
v2 = np.array([12, 3, 1, 1])
np.linalg.norm(v1 - v2)


8.94427190999916

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [ ]:
# 10.2.1

In [73]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

In [74]:
# a)
2*A

array([[ 4,  2, -2],
       [ 2, -2,  2]])

In [75]:
# b)
print(B - 2*A)

[[ 0 -4  3]
 [ 0 -2 -4]]


In [77]:
# c)
print(3*C - 2*E)

[[ 1  4]
 [ 2 -1]]


In [78]:
# d)
print(2*D - 3*C)

[[3 2]
 [2 3]]


In [79]:
#) e)
print(D.T + 2*D)

[[ 9 12]
 [12  9]]


In [80]:
# f)
print(2*C.T - 2*D.T)

[[-4 -4]
 [-4 -4]]


In [83]:
# i)
print(C @ D)

[[11 10]
 [10 11]]


In [84]:
# k)
print(C @ I)

[[1 2]
 [2 1]]


In [85]:
# l) 
print(A @ B.T)

[[5 2]
 [7 4]]


In [ ]:
10.2.2

In [90]:
A = np.array([[2, 3, 4], [5, 4, 1]])
print(A @ A.T)

[[29 26]
 [26 42]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [25]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [26]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [27]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
# The base attribute of the ndarry make it easy to tell if an array is a view or a copy. Base_attribute of a view returns the original array. 
# for a copy it returns None. 